baseURL = "https://t0muxx.github.io"
title = "t0muxx's blog"
theme = 'hugo-theme-nostyleplease'
languageCode = "en-us"
pluralizelisttitles = false 

[params]
    brand = "t0muxx's blog"                      # name of your site - appears in the sidebar
    # remote_brand_image = 'https://github.com/USERNAME.png' # path to a remote file
    brand_image = "/assets/img/cybercat.jpeg"    # path to the image shown in the sidebar
    description = "Swimming in cyberspace... Low level dev, malware technique, reverse and others stuff" # Used as default meta description if not specified in front matter
    dark_mode = true 
    favicon = "/assets/img/favicons/favicon.ico"
    menu = [
        # Dict keys:
            # Name:         The name to display on the menu.
            # URL:          The directory relative to the content directory.
            # HasChildren:  If the directory's files should be listed.  Default is true.
            # Limit:        If the files should be listed, how many should be shown.

        # SINGLE PAGE
        # Note that you must put your markdown file 
        # inside of a directory with the same name.

        # Example:
        # ... /content/about/about.md
        #{Name = "About", URL = "/about/", HasChildren = false},
        
        # ... /content/foo/_index.md
        # {Name = "Foo", URL = "/foo/", HasChildren = false},

        # LIST
        # This example has a subheading of "Recent"
        # and will display up to 5 items.

        # Example:
        # ... /content/posts/introducing-poison.md
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},

        # Example of a list without a subheading or limit.
        #{Name = "Projects", URL = "/projects/"},
    ]
    front_page_content = ["posts"]
    
    # Links to your socials.  Comment or delete any you don't need/use. 
    #discord_url = "https://discord.com"
    #email_url = "mailto://user@domain"
    #facebook_url = "https://facebook.com"
    #flickr_url = "https://flickr.com"
    github_url = "https://github.com/t0muxx"
    #gitlab_url = "https://gitlab.com"
    #instagram_url = "https://instagram.com"
    #linkedin_url = "https://linkedin.com"
    #mastodon_url = "https://mastodon.social"
    #matrix_url = "https://matrix.org"
    #telegram_url = "https://telegram.org"
    #tryhackme_url = "https://tryhackme.com"
    #twitter_url = "https://twitter.com"
    #xmpp_url = "https://xmpp.org"

    # NOTE: If you don't want to use RSS, comment or delete the following lines
    # Adds an RSS icon to the end of the socials which links to {{ .Site.BaseURL }}/index.xml
    rss_icon = true
    # Which section the RSS icon links to, defaults to all content. See https://gohugo.io/templates/rss/#section-rss
    rss_section = "posts"
